### ISSUE TITLE
Error when running warberry.py -a -T

### ISSUE THREAD

**Issue by belyache** [secgroundzero/warberry#71] opened 2016-11-13 20:03 UTC
I was struggling to figure out why the script would fail with:

Traceback (most recent call last):
  File "warberry.py", line 308, in <module>
    main()
  File "warberry.py", line 265, in main
    top_ports_scanner(CIDR, options.intensity, iface)
  File "/home/pi/WarBerry/warberry/src/core/scanners/top_port_scanner.py", line 34, in top_ports_scanner
    with open('../Results/ips_discovered', 'r') as h:
IOError: [Errno 2] No such file or directory: '../Results/ips_discovered'

I found that the file /home/pi/WarBerry/warberry/src/core/bypass/static.py has a > in the line:

 subprocess.call("sudo netdiscover -i %s -P -l ./src/discover | grep -P -o \'([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*? ' | grep -P -o \'[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' >../Results/ips_discovered" %ifname, shell = True)

This needs to be removed. Once the > is removed the file can be written as intended. The Line should look like this:

subprocess.call("sudo netdiscover -i %s -P -l ./src/discover | grep -P -o \'([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*? ' | grep -P -o \'[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' ../Results/ips_discovered" %ifname, shell = True)

Hope this helps. Once I got it running everything seems to work, although I haven't had much of a chance to test it.

Glenn

**Comment by fartsrainbows** [comment] 2016-11-16 01:59
I can reproduce this after running 'sudo ./warberry.py -C' to clear previous logs.

The problem is the the function /home/pi/WarBerry/warberry/src/core/scanners/top_port_scanner.py is trying to read the file ../Results/ips_discovered' before it is even created. 

@belyache The '>' is correct as it tells the bash shell to forward STDOUT to a file, by removing it you will break the command syntax, example:
(i have removed the greps to simplify the example)

/home/pi/WarBerry/warberry# netdiscover -i eth0 -P -l ./src/discover  ../Results/ips_discovered
Invalid extra argument: ../Results/ips_discovered

Netdiscover 0.3-beta7 [Active/passive arp reconnaissance tool]
Written by: Jaime Penalba <jpenalbae@gmail.com>

Where if you keep the '>' the command completes successfully and write output to the file.
/home/pi/WarBerry/warberry# netdiscover -i eth0 -P -l ./src/discover > ../Results/ips_discovered

/home/pi/WarBerry/warberry# cat ../Results/ips_discovered
 _____________________________________________________________________________
   IP            At MAC Address      Count  Len   MAC Vendor                   
 ----------------------------------------------------------------------------- 
 10.10.10.2         01    060   Unknown vendor
 10.10.10.110       01    060   Unknown vendor

**Comment by fartsrainbows** [comment] 2016-11-16 03:15
I am testing this as a fix, importing the os_enum module and running os_enum if live_ips file not found.

```
import nmap
import os,os.path
from src.utils.console_colors import *
src.core.enumeration.os_enum_ import *

def top_ports_scanner(CIDR,intensity,iface):
        print bcolors.OKGREEN + "      [ TOP TCP PORTS NETWORK SCANNER MODULE ]\n" + bcolors.ENDC
        if os.path.isfile('../Results/top_tcp'):
                print bcolors.WARNING + "[!] Top TCP Ports Results File Exists. Previous Results will be Overwritten" + bcolors.ENDC
        hostlist = []
        if os.path.isfile('../Results/live_ips'):
                with open('../Results/live_ips', 'r') as h:
                        hosts = h.readlines()
                        for host in hosts:
                                hostlist.append(host.strip())
        else:
                os_enum(iface, CIDR)
                with open('../Results/live_ips', 'r') as h:
                        hosts = h.readlines()
                        for host in hosts:
                                hostlist.append(host.strip())
        print "Beginning Scanning Subnet %s" %CIDR
        print " "
        nm = nmap.PortScanner()
        print "[+] Scanning Top 1000 TCP Ports in all hosts with %s intensity..." %intensity + "\n"
        arg = "-Pn " + intensity + " --top-ports 1000 --open -o ../Results/tcp_top -e " + iface
        for h in hostlist:
                nm.scan(hosts=h, arguments=arg)
                for host in nm.all_hosts():
                        print('----------------------------------------------------')
                        print host + nm[host].hostname() + " open TCP ports: "
                        for proto in nm[host].all_protocols():
                                lport = nm[host][proto].keys()
                                lport.sort()
                        for port in lport:
                                print bcolors.OKGREEN + ' [+] ' + bcolors.ENDC + '%s' %port`
```

**Comment by secgroundzero** [comment] 2016-11-18 18:52
@belyache can you please confirm if there are live ips in the network?

it seems to me you are trying to bypass a static ip filtering and its not working.

does it work with the default scans?

**Comment by secgroundzero** [comment] 2016-12-24 12:43
closing as no update was received

**Closed** 2016-12-24 12:43 UTC
